package foodapp.mybatis.model;

import java.util.List;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.USERNAME
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    private String username;

    private List<Shoporder> shoporders;

    public List<Shoporder> getShoporders() { return shoporders; };

    public void setShoporders(List<Shoporder> shoporders) { this.shoporders = shoporders; }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.USERNAME
     *
     * @return the value of PUBLIC.CUSTOMER.USERNAME
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.USERNAME
     *
     * @param username the value for PUBLIC.CUSTOMER.USERNAME
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }
}