package foodapp.mybatis.model;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.ID
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.NAME
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.ID
     *
     * @return the value of PUBLIC.ITEM.ID
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.ID
     *
     * @param id the value for PUBLIC.ITEM.ID
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.NAME
     *
     * @return the value of PUBLIC.ITEM.NAME
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.NAME
     *
     * @param name the value for PUBLIC.ITEM.NAME
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}