package foodapp.mybatis.dao;

import foodapp.mybatis.model.Shoporder;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ShoporderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPORDER
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPORDER
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    int insert(Shoporder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPORDER
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    Shoporder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPORDER
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    List<Shoporder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPORDER
     *
     * @mbg.generated Tue Apr 11 23:51:28 EEST 2023
     */
    int updateByPrimaryKey(Shoporder record);

    int addItem(@Param("itemId") Long itemId,@Param("shopOrderId") Long shopOrderId);
}